# Alertmanager Configuration

global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@backup-system.local'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alerts
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
      group_wait: 5s
      repeat_interval: 1h

    # Warning alerts - less urgent
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 4h

    # Backup-specific alerts
    - match:
        alertname: 'CriticalBackupFailures'
      receiver: 'backup-team'
      continue: true

# Inhibition rules - suppress certain alerts
inhibit_rules:
  # Suppress warning if critical is already firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Suppress backup warnings if application is down
  - source_match:
      alertname: 'ApplicationDown'
    target_match_re:
      alertname: '.*Backup.*'

# Receivers - notification endpoints
receivers:
  - name: 'default'
    email_configs:
      - to: 'admin@backup-system.local'
        headers:
          Subject: '[Backup System] Alert: {{ .GroupLabels.alertname }}'

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@backup-system.local,oncall@backup-system.local'
        headers:
          Subject: '[CRITICAL] Backup System Alert: {{ .GroupLabels.alertname }}'
        send_resolved: true
    # Slack webhook (optional)
    # slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'
    #     channel: '#critical-alerts'
    #     title: 'Critical Alert: {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'admin@backup-system.local'
        headers:
          Subject: '[Warning] Backup System Alert: {{ .GroupLabels.alertname }}'

  - name: 'backup-team'
    email_configs:
      - to: 'backup-team@backup-system.local'
        headers:
          Subject: '[Backup Alert] {{ .GroupLabels.alertname }}'
    # Microsoft Teams webhook (optional)
    # webhook_configs:
    #   - url: 'YOUR_TEAMS_WEBHOOK_URL'
