# Prometheus Configuration for Backup Management System

global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  external_labels:
    cluster: 'backup-management-system'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backup Management System application
  - job_name: 'backup-management-system'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # PostgreSQL/SQLite metrics (if using postgres_exporter)
  - job_name: 'database'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if using Redis for caching)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Backup storage metrics (custom exporter)
  - job_name: 'backup-storage'
    static_configs:
      - targets: ['storage-exporter:9200']
    scrape_interval: 60s

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     queue_config:
#       capacity: 10000
#       max_shards: 10
#       min_shards: 1
#       max_samples_per_send: 5000

# Remote read configuration
# remote_read:
#   - url: "http://remote-storage:9201/read"
